name: Publish Mutation Report

on:
  push:
    branches:
      - main   # Cambia si usas otra rama principal

jobs:
  mutation_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          cd Bank
          dotnet restore

      - name: Build solution
        run: |
          cd Bank
          dotnet build --no-restore --configuration Release

      - name: Install Stryker CLI tool
        run: dotnet tool install -g dotnet-stryker

      - name: Run Stryker mutation tests
        run: |
          cd Bank/Bank.Domain.Tests
          dotnet stryker --reporter html --output ../../StrykerOutput

      - name: Deploy mutation report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./StrykerOutput/reports
